spring:
    jpa:
        hibernate:
            ddl-auto: update   # or create-drop for dev
        show-sql: true
    application:
        name: taco-cloud
    datasource:
        url: jdbc:h2:mem:tacocloud
        driver-class-name: org.h2.Driver
        username: sa
        password:
    h2:
        console:
            enabled: true
            path: /h2-console